# version: '3.4' # Define the version of Docker Compose to use

# services: #defines services that will be run by Docker compose
#   nginx: 
#    build: #tells Docker Compose to build the Docker image for the nginx service
#     context: . #specifies the directory that Docker will use to build the image.
#     dockerfile: requirments/nginx/Dockerfile #specifies the path to the Dockerfile that will be used to build the image
#   container_name: nginx
#   depends on:
#    -wordpress #specifies that the nginx container should wait for the wordpress container to be ready before starting
#   ports: 
#    -"443:443" #the host machine's port 443 will be mapped to the container's port 443
#   networks:
#    -inception #nginx container will be connected to a network named inception
#   volumes: #allow you to persist data or share data between the host and containers, allows you to pass configuration files into the container.
#    -./requirments/nginx/conf/:/etc/nginx/http.d/
#    -./requirments/nginx/tools:/etc/nginx/ssl/
#    - wp-volume:/var/www/
#   env_file: #a file containing environment variables that will be loaded into the container
#    -.env
#   restart: always #always restarts the container if it stops or crashes

version: "3"

services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: ./requirements/nginx/
    volumes:
      - wp_volume:/var/www/html/
    restart: always
    networks:
      - bridge-network
    env_file:
      - .env
    ports:
      - "443:443"

 mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    volumes:
      - db_volume:/var/lib/mysql/
    networks:
      - bridge-network
    env_file:
      - .env
    restart: always

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress/
    volumes:
      - wp_volume:/var/www/html/
    restart: always
    networks:
      - bridge-network
    env_file:
      - .env

volumes:
  wp_volume:
    driver: local
    driver_opts:
      device: /home/rmkrtchy/data/wordpress
      o: bind
      type: none
  db_volume:
    driver: local
    driver_opts:
      device: /home/rmkrtchy/data/mariadb
      o: bind
      type: none

networks:
  bridge-network:
    driver: bridge




