version: "3"

services:
    mariadb:
        build: ./requirements/mariadb/
        image: mariadb
        container_name: ruzo_mariadb
        env_file:
            - .env
        networks:
            - inception
        volumes:
            - mariadb_data:/var/lib/mysql/
        restart: on-failure
    wordpress:
        build:
            context: ./requirements/wordpress/
        image: wordpress
        container_name: ruzo_wordpress
        env_file:
            - .env
        networks:
            - inception
        volumes:
            - wordpress_data:/var/www/wordpress/
        restart: on-failure
        depends_on:
            - mariadb
    nginx:
        build:
            context: ./requirements/nginx/
        image: nginx
        container_name: ruzo_nginx
        env_file:
            - .env
        networks:
            - inception
        volumes:
            - wordpress_data:/var/www/wordpress/
        restart: on-failure
        ports:
            - "443:443"
        depends_on:
            - wordpress

networks:
    inception:

volumes:
    wordpress_data:
        driver_opts:
            device: $HOME/data/wordpress
            o: bind
            type: none
    mariadb_data:
        driver_opts:
            device: $HOME/data/mariadb
            o: bind
            type: none
